### ISSUE TITLE
Сертификаты разбить по категория

### ISSUE THREAD

**Issue by vgulaev** [ptstmn/ptstmn.github.io#2]
Категории как Дефектоскопия
Категории: 
ISO 9001 ( 2 оставшихся )
Лабаратория НК и ТД ( Неразрушымый контоль 4 сертификата )
Харбендинг ( Сертификаты компании Caslolin )

**Comment by movis08** [comment]
Разбить на категории...
Уточните. Нужно чтобы каждая категория была на отдельной странице. Или все было на этой странице. Просто разбито на разделы (визуально)
